### ISSUE TITLE
[Linux] Support for GCC compiler?

### ISSUE THREAD

**Issue by derVedro** [attltb/UFBL#1]
I have one use case in mind where I am dealing with one bit per pixel blobs. So I would gladly play around with your implementation. But unfortunately gcc doesn't compile it under linux. Looks like you are using some special MSVC intrinsics headers. Maybe I'm completely wrong, I'm not much into c++. Anyway, will it be possible to use UFBL with linux?

**Comment by attltb** [comment]
Using compiler specific function is inevitable for UFBL since there are no standard functions for [Find First Set](https://en.wikipedia.org/wiki/Find_first_set) in C++. 
Someday I'll make UFBL cross-platform using CMake but I'm still not very comfortable with makefile syntax. 

If you're in a hurry, there is simple way to make my source files compatible with GCC environment.

1. Delete `#include <intrin0.h>`
2. Add `#include <stddef.h>`, `#include <stdint.h>` instead.
3. Fix every parts in the source code which are like
```
while (!_BitScanForward64(&bitpos, working_bits)) { ... }
```
to
```
while (!working_bits) { ... }
bitpos = __builtin_ffsll(working_bits);
```
. This changes 64-bit MSVC function `_BitScanForward64` to 64-bit GCC function `__builtin_ffsll`. 
Similarly, you can change any parts including
```
while (!_BitScanForward64(&bitpos, working_bits)) {  ... }
```
to 
```
while (!working_bits) { ... }
bitpos = __builtin_ffsl(working_bits);
```

I think this little change will work fine. Thank you.

**Comment by derVedro** [comment]
First thank you for support. As I have already written I am not good with C++. So I still have some troubles making things right. I redifened `__int64` as `long long`, then removed all four `_BitScanForward64` in whiles and added `__builtin_ctzll` after each loop. First I tried `__builtin_ffsll` but that function adds an extra one to the index. But something goes wrong — the runs (as I understand right what a run is) are **flipped in alignment chunks**. If you have some time, I made a gcc branch and you can look at _fubar_test.cpp_.

**Comment by attltb** [comment]
Using `__builtin_ctzll` is right. It's my mistake. By the way, what do you mean by runs are flipped? Your test program works without any problem for me. It does exactly what it should do.

If I got it right, it depends on your purpose. My codes are to find and label connected white (bit 1) blobs in input image. If you want to find connected black(bit 0) parts in white background, my current codes would not work for you. For now, the starting position and the ending position are founded by these codes.

```
//find starting position
while (!working_bits) {
	bits++, basepos += 64;
	if (bits == bit_final) { ... }
	working_bits = *bits;
}
bitpos = __builtin_ctzll(working_bits);
```

```
//find ending position
working_bits = (~working_bits) & (0xFFFFFFFFFFFFFFFF << bitpos);
while (!working_bits) {
	bits++, basepos += 64;
	if (bits == bit_final) { ... }
	working_bits = ~(*bits);
}
bitpos = __builtin_ctzll(working_bits);
working_bits = (~working_bits) & (0xFFFFFFFFFFFFFFFF << bitpos);
```

As you can see, it flips the working bits before finding ending position since `__builtin_ctzll` can not be used directly to find first 0. If you want to find linear chunks of 0, these two codes should be exchanged. I note that some additional change might also be needed to check boundary condition correctly.

**Comment by attltb** [comment]
I'm sorry. I just got what did you mean by runs are flipped now. Shapes of letters are indeed flipped. When we write binary numbers, usually the most significant bit comes first. In my program, the least significant bit comes first.

For me, types like `__int64` are just a way to save 2D binary data. They are essentially bit-arrays, not a number. Unlike for the binary numbers, I think that the least-significant-bit-first format is better for bit-arrays. It's also easier to compress an image with this format, so I think this format is more natural. 

I don't know your situation. In my opinion, the best option is just to change the input binary data to least-significant-bit-first format. I believe it's more natural in general.

**Comment by derVedro** [comment]
Yes, you're right. I did not thought about endianness. I deal with some portable bitmap files (P4 pbm). This is a pretty simple format that consist of a header with dimensions and a binary blob that is big-endian encoded, each byte for eight pixels.

**Comment by attltb** [comment]
If the input image is big-endian encoded, I think the simplest solution is just reversing the processing order, like this.

```
//find starting position
while (!working_bits) {
	bits--, basepos += 64;
	if (bits < bits_first) { ... }
	working_bits = *bits;
}
bitpos = __builtin_ctzll(working_bits);
```

```
//find ending position
working_bits = (~working_bits) & (0xFFFFFFFFFFFFFFFF << bitpos);
while (!working_bits) {
	bits--, basepos += 64;
	if (bits < bits_first) { ... }
	working_bits = ~(*bits);
}
bitpos = __builtin_ctzll(working_bits);
working_bits = (~working_bits) & (0xFFFFFFFFFFFFFFFF << bitpos);
```

The output image will be left and right reversed, but the structure of the image will not change at least. Depending on your purpose (for example, if the labelled image generated by UFBL is just an intermediate data to get some other final result), this itself may be enough. 

If you want correct result, you may have to change the part of the code to generate output, too. Like from

```
for(...) {
	...
	unsigned short start_pos = runs->start_pos;
	...
	unsigned short end_pos = runs->end_pos;
	...
}
```

to

```
for(...) {
	...
	unsigned short start_pos = img_width - runs->start_pos;
	...
	unsigned short end_pos = img_width - runs->end_pos;
	...
}
```

Many parts of my code will also have to be changed since the boundary condition is different now. Perhaps the right edge of the image (which will be processed firstly in this plan) may have to be treated completely differently. For 10 digits binary numbers, 10th bits comes first, not 32nd bits as usual.

**Comment by attltb** [comment]
If the input image is big-endian for eight pixels, I think this will be the best option.

```
//find starting position
while (!working_bits) {
	bits--, basepos += 64;
	if (bits < bits_first) { ... }
	working_bits = __builtin_bswap64(*bits);
}
bitpos = __builtin_ctzll(working_bits);
```

```
//find ending position
working_bits = (~working_bits) & (0xFFFFFFFFFFFFFFFF << bitpos);
while (!working_bits) {
	bits--, basepos += 64;
	if (bits < bit_first) { ... }
	working_bits = __builtin_bswap64(~(*bits));
}
bitpos = __builtin_ctzll(working_bits);
working_bits = (~working_bits) & (0xFFFFFFFFFFFFFFFF << bitpos);
```

The output image will be left-right reversed but the structure of the image will be remain unchanged. Depending on your purpose, this might be enough. If not, you have to change the generating output parts, too. 

I note that the additional `__builtin_bswap64` call needs because in little-endian systems, *bytes* in `long long` or `__int64` variable are saved in little-endian order. If your system is big-endian, the call should be omitted. (The pbm format does saves *bits in a byte* with big-endian order, but saves *bytes* with little-endian order. )

**Comment by derVedro** [comment]
Thank you for the your time and help. I need some time to dig through. May be it would be easy for me if I encode the bytes from the blob to big-endian before. I need some time to try it out. Thank you again!

**Comment by attltb** [comment]
UFBL now supports platform independence and p4 pbm as input.
